# file: roles/elasticsearchtier/tasks/main.yml
- include_tasks: java.yml
- include_tasks: elasticsearch-yum-repo.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
- include_tasks: elasticsearch-apt-repo.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
- include_tasks: elasticsearch.yml

