# file: site.yml
- import_playbook: webservers.yml
- import_playbook: dbservers.yml
- import_playbook: queueservers.yml
- import_playbook: elasticsearchservers.yml
  when: elasticsearch|default(false)|bool == true
- import_playbook: cleanup.yml
