# file: roles/webtier/tasks/git-repositories.yml
- name: Add repository users to group www-data
  tags: nginx
  shell: usermod -aG www-data {{ item.value.repository.user | default(root) }}
  with_dict: "{{ virtualhosts }}"
  when:
    - virtualhosts is defined

- name: Clone repositories
  tags: git-repositories
  git:
    repo: "{{ item.value.repository.url }}"
    version: "{{ item.value.repository.branch | default(master) }}"
    dest: "/var/www/{{ item.key }}"
    accept_hostkey: yes
    force: yes
  with_dict: "{{ virtualhosts }}"
  become_user: "{{ item.value.repository.user | default(root) }}"
  when:
    - virtualhosts is defined
  notify:
    - Restart nginx

- name: Set repository user as the directory owner
  tags: git-repositories
  file: path="/var/www/{{ item.key }}" recurse=yes owner="{{ item.value.repository.user }}"
  with_dict: "{{ virtualhosts }}"
  when:
    - virtualhosts is defined
