# file: roles/webtier/tasks/letsencrypt.yml
- name: Install certbot
  tags: letsencrypt
  yum: name=certbot state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Enable cerbot repository permanently
  tags: cerbot
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Upgrade all packages
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install certbot
  tags: letsencrypt
  apt: name=python-certbot-nginx state=present
  notify:
    - Restart nginx
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Check if Diffie-Hellman group exists
  tags: letsencrypt
  stat:
    path: /etc/ssl/certs/dhparam.pem
  register: group_exists

- name: Generate a strong 2048 bit Diffie-Hellman group
  tags: letsencrypt
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048
  when: group_exists.stat.exists == false

- name: Check existence of virtualhosts certificates
  tags: letsencrypt
  stat:
    path: /etc/letsencrypt/live/{{ item.value.servernames[0] }}/fullchain.pem
  with_dict: "{{ virtualhosts }}"
  register: certs_check
  when:
    - virtualhosts is defined

- name: Install / renew virtualhosts certificates
  tags: letsencrypt
  shell: certbot certonly --noninteractive --webroot --email {{ letsencrypt_email }} --agree-tos --renew-by-default -w /var/www/{{ item.item.key }}/public -d {{ item.item.value.servernames | join(" -d ") }}
  with_items: "{{ certs_check.results }}"
  notify:
    - Restart nginx
  when: 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - virtualhosts is defined
    - item.stat.exists == False

- name: Install / renew virtualhosts certificates
  tags: letsencrypt
  shell: certbot --nginx --noninteractive --email {{ letsencrypt_email }} --agree-tos --renew-by-default -d {{ item.item.value.servernames | join(" -d ") }} --server https://acme-v02.api.letsencrypt.org/directory
  with_items: "{{ certs_check.results }}"
  notify:
    - Restart nginx
  when: 
    - ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    - virtualhosts is defined
    - item.stat.exists == False

- name: Check existence of phpmyadmin certificate
  tags: letsencrypt
  stat:
    path: /etc/letsencrypt/live/{{ phpmyadmin_virtualhost }}/fullchain.pem
  register: pma_check
  when:
    - phpmyadmin_virtualhost is defined
    - phpmyadmin_https|default(true)|bool == true

- name: Install / renew phpmyadmin certificates
  tags: letsencrypt
  shell: certbot certonly --noninteractive --webroot --email {{ letsencrypt_email }} --agree-tos --renew-by-default -w /var/www/phpmyadmin -d {{ phpmyadmin_virtualhost }}
  notify:
    - Restart nginx
  when: 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - virtualhosts is defined
    - pma_check.stat.exists == False

- name: Install / renew phpmyadmin certificate
  tags: letsencrypt
  shell: certbot --nginx --noninteractive --email {{ letsencrypt_email }} --agree-tos --renew-by-default -d {{ phpmyadmin_virtualhost }} --server https://acme-v02.api.letsencrypt.org/directory
  notify:
    - Restart nginx
  when:
    - ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    - virtualhosts is defined
    - pma_check.stat.exists == False

- name: Add auto renewal for certificates to crontab
  tags: letsencrypt
  cron:
    name: "Weekly check for certificates"
    special_time: weekly
    job: /usr/bin/certbot renew --post-hook "service nginx restart"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'