# file: roles/webtier/tasks/main.yml
- include_tasks: javascript.yml
  when: nodejs|default(true)|bool == true or yarn|default(true)|bool == true
- include_tasks: remi.yml
  when: 
    - php|default(true)|bool == true
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
- include_tasks: ondrej.yml
  when: 
    - php|default(true)|bool == true
    - ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'  
- include_tasks: php.yml
  when: php|default(true)|bool == true
- include_tasks: php-fpm.yml
  when: php|default(true)|bool == true
- include_tasks: composer.yml
  when: composer|default(true)|bool == true
- include_tasks: nginx.yml
  when: nginx|default(true)|bool == true
- include_tasks: git-repositories.yml
- include_tasks: dotenv.yml
- include_tasks: cron.yml
- include_tasks: firewalld.yml
  when: firewalld|default(false)|bool == true
# - include_tasks: ssl.yml
#   when: ssl|default(false)|bool == true
- include_tasks: letsencrypt.yml
  when: ssl|default(false)|bool == true
- include_tasks: nginx-ssl.yml
  when: nginx|default(true)|bool == true and ssl|default(false)|bool == true
- include_tasks: redis.yml
  when: redis|default(false)|bool == true
- include_tasks: selinux.yml
  when: 
    - selinux|default(true)|bool == true
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

