# file: roles/webtier/tasks/nginx.yml
- name: Make sure nginx ssl virtual hosts are configured
  tags: nginx
  template: src=nginx-ssl-virtualhost.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: "{{ virtualhosts }}"
  notify:
    - Restart nginx