# file: roles/webtier/tasks/nginx.yml
- name: Check if apache2 is installed
  tags: nginx
  stat:
    path: /usr/sbin/apache2
  register: apache2_binary

- name: Stop apache2
  tags: nginx
  when: apache2_binary.stat.exists == true
  service: name=apache2 state=stopped enabled=no

- name: Install nginx
  tags: nginx
  yum: name=nginx state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install nginx
  tags: nginx
  apt: name=nginx state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure nginx is running and is started on boot
  tags: nginx
  service: name=nginx state=started enabled=yes

- name: Check existence of virtualhost ssl certificates
  tags: nginx
  stat:
    path: /etc/letsencrypt/live/{{ item.value.servernames[0] }}/fullchain.pem
  with_dict: "{{ virtualhosts }}"
  register: vhost_certs

- name: Make sure nginx virtual hosts are configured
  tags: nginx
  template: src=nginx-virtualhost.conf.j2 dest=/etc/nginx/conf.d/{{ item.item.key }}.conf
  with_items: "{{ vhost_certs.results }}"
  notify:
    - Restart nginx
  when:
    - item.stat.exists == false

- name: Check existence of phpmyadmin ssl certificate
  tags: nginx
  stat:
    path: /etc/letsencrypt/live/{{ phpmyadmin_virtualhost }}/fullchain.pem
  register: pma_cert
  when:
    - phpmyadmin == true
    - phpmyadmin_virtualhost is defined

- name: Create nginx virtual host for phpmyadmin
  tags: nginx-phpmyadmin
  template: src=nginx-pma-virtualhost.conf.j2 dest=/etc/nginx/conf.d/phpmyadmin.conf
  when: phpmyadmin_virtualhost is defined
  notify:
    - Restart nginx
  when:
    - pma_cert is defined
    - pma_cert.stat.exists == false
    
- name: Set permissions on /var/www
  tags: nginx
  file: path=/var/www owner=root group=www-data mode=ug=rwX,o=rX recurse=yes
  when:
    - pma_cert is defined
    - pma_cert.stat.exists == false