# file: roles/webtier/tasks/nginx.yml
- name: Check if apache2 is installed
  tags: nginx
  stat:
    path: /usr/sbin/apache2
  register: apache2_binary

- name: Stop apache2
  tags: nginx
  when: apache2_binary.stat.exists == true
  service: name=apache2 state=stopped enabled=no

- name: Install nginx
  tags: nginx
  yum: name=nginx state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install nginx
  tags: nginx
  apt: name=nginx state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure nginx is running and is started on boot
  tags: nginx
  service: name=nginx state=started enabled=yes

- name: Make sure nginx virtual hosts are configured
  tags: nginx
  template: src=nginx-virtualhost.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: "{{ virtualhosts }}"
  notify:
    - Restart nginx
    
- name: Set permissions on /var/www
  tags: nginx
  file: path=/var/www owner=root group=www-data mode=ug=rwX,o=rX recurse=yes