# file: roles/webtier/tasks/ssl.yml
- name: Check if RSA key exists
  tags: letsencrypt
  stat:
    path: /etc/ssl/certs/genrsa.pem
  register: group_exists

- name: Generate a strong 2048 bit RSA key
  tags: letsencrypt
  shell: openssl genrsa -out /etc/ssl/certs/genrsa.pem 2048
  when: group_exists.stat.exists == false

- name: Create a challenge for virtualhosts using an account key from a variable.
  acme_certificate:
    account_key_src: /etc/ssl/certs/genrsa.pem
    csr: /etc/pki/cert/csr/{{ item.key }}.csr
    dest: /etc/httpd/ssl/{{ item.key }}.crt
    fullchain_dest: /etc/httpd/ssl/{{ item.key }}-fullchain.crt
    terms_agreed: yes
    validate_certs: no
  register: challenge
  with_dict: "{{ virtualhosts }}"

# perform the necessary steps to fulfill the challenge
# for example:
#
- copy:
    dest: /var/www/html/{{ challenge['challenge_data'][item.item.key]['http-01']['resource'] }}
    content: "{{ item['challenge_data'][item.item.key]['http-01']['resource_value'] }}"
    when: item is changed
    with_dict: "{{ challenge.results }}"

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  acme_certificate:
    account_key_src: /etc/pki/cert/private/account.key
    account_email: myself@sample.com
    src: /etc/pki/cert/csr/sample.com.csr
    cert: /etc/httpd/ssl/sample.com.crt
    fullchain: /etc/httpd/ssl/sample.com-fullchain.crt
    chain: /etc/httpd/ssl/sample.com-intermediate.crt
    challenge: dns-01
    acme_directory: https://acme-v01.api.letsencrypt.org/directory
    remaining_days: 60
    
    account_key_src: /etc/pki/cert/private/account.key
    account_email: "{{ letsencrypt_email }}"
    csr: /etc/pki/cert/csr/{{ item.key }}.csr
    dest: /etc/httpd/ssl/{{ item.key }}.crt
    fullchain_dest: /etc/httpd/ssl/{{ item.key }}-fullchain.crt
    chain_dest: /etc/httpd/ssl/{{ item.key }}-intermediate.crt
    data: "{{ item }}"
  with_dict: "{{ challenge.results }}"