# file: roles/webtier/tasks/ssl.yml
- name: Check acme is installed
  tags: ssh
  shell: wget -O -  https://get.acme.sh | sh

- name: Install acme
  tags: ssh
  shell: wget -O -  https://get.acme.sh | sh

- name: Enable acme
  tags: ssh
  shell: source ~/.bashrc

- name: Issue certificates
  tags: ssh
  shell: acme.sh --issue -d {{ item.value.servernames | join(" -d ") }} -w /var/www/{{ item.key }}/public
  with_dict: "{{ virtualhosts }}"
  when: item.value.https|default(true)|bool == true
  register: issued_certs

- name: Install certificates
  tags: ssh
  shell: acme.sh --install-cert -d {{ item.value.servernames | join(" -d ") }} --key-file=/etc/nginx/{{ item.key }}/key.pem --fullchain-file=/etc/nginx/{{ item.key }}/key.pem --reloadcmd "service nginx force-reload"
  with_dict: "{{ virtualhosts }}"
  notify:
    - Restart nginx
  when: 
    - item.value.https|default(true)|bool == true
    - issued_certs|bool == true
