# file: roles/common/tasks/main.yml

- name: Make sure epel-repository is installed
  yum: name=epel-release state=present
  tags: epel
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- include_tasks: remi.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Upgrade all packages
  yum: name=* state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Upgrade all packages
  apt: upgrade=full update_cache=yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure git is installed
  tags: git
  yum: name=git state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Make sure git is installed
  tags: git
  apt: name=git state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure unzip is installed
  tags: unzip
  yum: name=unzip state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Make sure unzip is installed
  tags: unzip
  apt: name=unzip state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure curl is installed
  tags: curl
  apt: name=curl state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Make sure curl is installed
  tags: curl
  apt: name=curl state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Remove require tty
  lineinfile:
    dest: /etc/sudoers
    line: 'Defaults    requiretty'
    state: absent

- include_tasks: ntp.yml
- include_tasks: selinux.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
- include_tasks: yum-cron.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
- include_tasks: cron-apt.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
- include_tasks: swap.yml