# file: roles/webtier/tasks/phpmyadmin.yml
- name: Install phpmyadmin
  tags: phpmyadmin
  apt: name=phpmyadmin state=present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install phpmyadmin
  tags: phpmyadmin
  apt: name=phpmyadmin state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Expose phpmyadmin
  tags: phpmyadmin
  file: src=/usr/share/phpmyadmin dest={{ phpmyadmin_directory | default('/var/www/html') }} state=link

- name: Ensure session directory exist
  tags: phpmyadmin
  file: path=/var/lib/php/session mode=ug=rwX,o=wX state=directory

- name: Restart mysql
  service: name=mysql state=restarted